### ISSUE TITLE
ExampleFilter

### ISSUE THREAD

**Issue by theadactyl** [tensorflow/tfx-addons#16]
Component to filter examples of a TF-record dataset using a user-defined predicate function

cc @sngahane

**Comment by rcrowe-google** [comment]
Not up to date with TFXIO. Uses predicate to filter examples, which are represented as dicts. Needs to be refactored to make more robust. Similar to old Transform. Ryan to write proposal.
cc @rclough

**Comment by pselden** [comment]
Given the discussion around additional IO costs of making this a new component and the general consensus that this would be an generically useful addition for all ExampleGens, what would be the process for getting this considered into core TFX as part of ExampleGen instead of as an addon?

In the mean time we could continue on with this to get it usable.

**Comment by sayakpaul** [comment]
@deep-diver this sounds like something we have done something similar in our data drift project. Would you like to join forces here?
