### ISSUE TITLE
Schema curation custom component

### ISSUE THREAD

**Issue by theadactyl** [tensorflow/tfx-addons#8]

**Comment by rcrowe-google** [comment]
This project applies Python user code to a schema which is produced by SchemaGen, in order to curate the schema based on domain knowledge.  For example, if the range of a numeric feature is actually greater than what SchemaGen infers, then the range in the schema can be adjusted.  Or if there are valid categorical values that are not included in the inferred schema, they can be added.  This will include a user-supplied module file which contains the user code for curating the schema.  The user code will likely make heavy use of the [TFDV library](https://www.tensorflow.org/tfx/data_validation/api_docs/python/tfdv).
